name: 'Moderne Publish'
description: 'Publish your LST files to the Moderne Platform'
inputs:
  version:
    description: 'Moderne CLI version'
    required: false
    default: 'v0.0.18'
  publishUrl:
    description: 'Artifact Manager URL to publish the -ast.jar files'
    required: true
  publishUser:
    description: 'username for the artifact manager'
    required: true
  publishPwd:
    description: 'password for the artifact manager'
    required: true
  mvnPluginVersion:
    description: 'Moderne Maven plugin version'
    required: false
    default: 'LATEST'
  gradlePluginVersion:
    description: 'Moderne Gradle plugin version'
    required: false
    default: 'latest.release'
  mvnSettingsXML:
    description: 'Maven settings XML location with the credentials to download dependencies'
    required: false
    default: ''
  activeStyle:
    description: 'OpenRewrite formating style for fixes'
    required: false
    default: ''
  buildAction:
    description: 'Additional build tool tasks/targets to execute first for Maven and Gradle builds'
    required: false
    default: ''
  path:
    description: 'The path to use. By default the GITHUB_WORKSPACE'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
